[workspace]
resolver = "2"
members = [
    "slab-app/src-tauri",
    "slab-diffusion", 
    "slab-diffusion-sys",
    "slab-libfetch",
    "slab-llama",
    "slab-llama-sys",
    "slab-whisper",
    "slab-whisper-sys",
    "slab-core"
]

exclude = [
    "slab-app/src",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
description = "slab ML"
repository = "https://github.com/Cyberhan123/slab.rs"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "Apache-2.0"

[workspace.dependencies]
slab-diffusion-sys = { path = "./slab-diffusion-sys", package = "slab-diffusion-sys", version = "0.0.1" }
slab-diffusion = { path = "./slab-diffusion", package = "slab-diffusion", version = "0.0.1" }
slab-llama = { path = "./slab-llama", package = "slab-llama", version = "0.0.1" }
slab-llama-sys = { path = "./slab-llama-sys", package = "slab-llama-sys", version = "0.0.1" }
slab-whisper = { path = "./slab-whisper", package = "slab-whisper", version = "0.0.1" }
slab-whisper-sys = { path = "./slab-whisper-sys", package = "slab-whisper-sys", version = "0.0.1" }
slab-libfetch={ path = "./slab-libfetch", package = "slab-libfetch", version = "0.0.1" }

anyhow = "1.0.101"
bindgen = "0.72.1"
flate2 = "1.1.9"
libloading = "0.8.9"
reqwest = { version = "0.13.2", features = ["stream", "native-tls", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4.44"
tokio = { version = "1.49.0", features = ["full"] }
zip = { version = "4.6.1", default-features = false, features = ["deflate"] }
hf-hub = "0.4.1"
thiserror = "2.0.18"